config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'

  root 'home#index'

  resources :users

  resources :cards do
    post 'check_answer', to: 'home#check_answer'
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete 'oauth/:provider' => 'oauths#destroy', :as => :delete_oauth

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  validates :original_text, :translated_text, :review_date, presence: true
  validate :same_words, on: :create
  belongs_to :user, optional: true
  scope :unreviewed, -> { where('review_date <= ?', Date.today) }
  scope :random_order, -> { unreviewed.order(Arel.sql('random()')) }
  mount_uploader :pic, PicUploader

  def same_words
    if original_text.casecmp(translated_text.downcase).zero?
      errors.add(:translated_text, 'Translated text cannot equal original text')
    end
  end

  def self.random
    random_order.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  has_many :cards

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:edit, :show, :update, :destroy]

  def index
    @cards = Card.all
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def show
  end

  def create
    @card = Card.new(card_params)
    @card.review_date = Date.today #+ 3.days
    if @card.save
      redirect_to cards_path
    else
      render 'new'
    end
  end

  def update
    @card.update(card_params)
    redirect_to cards_path
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :pic)
  end

  def set_card
    @card = Card.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require_relative '../services/levenstein.rb'

  def index
    @card = Card.random if current_user
  end

  def check_answer
    @card = Card.find(params[:card_id])
    checker = CheckAnswer.new()
    if params[:answer] == @card.original_text
      result = checker.correct_answer(@card)
    elsif checker.mistype_check(params[:answer], @card.original_text)
      result = checker.mistype_answer(params[:answer], @card)
    else
      result = checker.incorrect_answer(@card)
    end
    redirect_to(root_path, notice: result)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    redirect_to(:root, notice: 'User was successfully created') if @user.save
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card, :html => {:multipart => true} do |f| %>
  <br>
  	Original
  	<p> <%= f.input :original_text, label: false %>
  <br>
  	Translated
  	<p> <%= f.input :translated_text, label: false %>
  <br>
      Add picture: 
      <%= f.file_field :pic %>   
  <br>   
    <%= f.button :submit %>
<% end %>

app/views/cards/edit.html.erb
<h2>Update Card</h2>
<%= render partial: 'form' %>

app/views/cards/index.html.erb
<table>
  <tr>
    <th>Original</th>
    <th>Translated</th>
    <th>Review date</th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.to_formatted_s(:rfc822) %></td>
      <td><%= link_to "edit card", edit_card_path(card) %></td>
      <td><%= link_to "delete card", card_path(card), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h2>New Card</h2>
<%= render partial: 'form' %>

app/views/cards/show.html.erb
<h1><%= @card.original_text %></h1>
Original text: <%= @card.original_text %>
Translated text: <%= @card.translated_text %>
<%= image_tag @card.pic_url(:thumb).to_s %>
Review date: <%= @card.review_date %>
<%= link_to "Edit", edit_card_path(@card) %>
<%= link_to "Delete", card_path(@card), :method => :delete, :confirm => "Are you sure?" %>
<%= link_to "Back", user_path(current_user) %>

app/views/home/_form.html.erb
<%= form_for @card, url: card_check_answer_path(@card), method: :post do |card| %>
  <div>
    <%= @card.original_text %>
  </div>
  <p>
  <div>
    <%= @card.translated_text %>
  </div>
  <p>
  <div>
    <%= @card.review_date %>
  </div>
  <p>
  <p><%= image_tag @card.pic_url(:thumb).to_s %>
  <div>
    <%= text_field_tag 'answer', nil %>
    <%= submit_tag "Check answer", method: 'check_answer' %>
  </div>
<% end %>

app/views/home/index.html.erb
<head>
  <title>Флэшкарточкер</title>
  <link rel="stylesheet" href="application.css">
</head>
<body>
  <section id="container">
    <section>
      <p style="font-size: 22px;">
        World's best flashcard manager. 
      </p>
    </section>
<b><font color="blue"><%= flash[:notice] %></font>
<% if @card.present?  %>
<div id="trainer">
  <%= render partial: 'form' %>
</div>
<% elsif current_user.present? %>
<p> No cards for today!
<% end %> 
  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container">
      
      <header class="clearfix">
        <h1><%= link_to "Flashcards", root_path %></h1>
        <ul class="navigation-links">
          <li><%= link_to "All cards", cards_path %></li>
          <li><%= link_to "Add card", new_card_path %></li>
        </ul>
        <div id="nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
      <%= link_to 'Login with Github', auth_at_provider_path(:provider => :github) %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
      </header>
     
    </section>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Sign in</h1>

<%= form_tag user_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn btn-large btn-primary" %>
  </div>
<% end %>
New user?
<%= link_to 'Sign up now!', new_user_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>